# Generated by Django 4.1.7 on 2023-03-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonycrudesystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='idnum',
            field=models.IntegerField(),
        ),
    ]
